<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<PropertyGroup>
		<!--<PublishAot>true</PublishAot>-->
		<InvariantGlobalization>true</InvariantGlobalization>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<!--NON-AOT-->
		<SelfContained>true</SelfContained>
		<PublishSingleFile>true</PublishSingleFile>
		<PublishReadyToRun>false</PublishReadyToRun>
		<!--Size-->
		<DebugType>none</DebugType>
		<EventSourceSupport>false</EventSourceSupport>
	</PropertyGroup>

	<PropertyGroup>
		<Version>1.0.0</Version>
		<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\WOWCAM.Core\WOWCAM.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\..\..\wowcam.xml.sample" Link="wowcam.xml">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
