<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<PropertyGroup>
		<Version>1.0.0</Version>
		<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
		<AssemblyName>WowcamWinUI</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\WOWCAM.Core\WOWCAM.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\..\..\wowcam.xml.sample" Link="wowcam.xml">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
